import time
import random
import turtle
import os

colors = ["white", "red", "blue", "green"]
width = 1000
height = 600
speed = 10
back_ground_color = "black"
line_color = "white"
Screen_title = "Screen test"
hide_tutle = 1
done_spins = 0
loops = 1000

screen = turtle.Screen()
screen.setup(width, height)
screen.bgcolor(back_ground_color)
screen.title(Screen_title)

def rect():
    turtle.forward(400)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(400)
    turtle.right(90)
    turtle.forward(200)

def brige():
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(100)

def building():
    turtle.penup()
    turtle.back(200)
    turtle.left(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.pendown()
    rect()
    turtle.penup()
    turtle.right(180)
    turtle.forward(250)
    turtle.left(90)
    turtle.pendown()
    brige()
    turtle.penup()
    turtle.right(90)
    turtle.forward(200)
    turtle.pendown()
    brige()
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(200)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(400)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(180)
    turtle.forward(150)
    turtle.left(90)
    turtle.forward(400)
    turtle.left(90)
    turtle.forward(250)
    turtle.left(90)
    turtle.forward(400)
    turtle.back(200)
    turtle.right(90)
    turtle.forward(100)
    turtle.back(200)
    turtle.right(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(200)
    turtle.left(90)
    turtle.forward(200)
    turtle.left(90)
    turtle.forward(200)
    turtle.penup()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(250)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(450)
    turtle.right(90)
    turtle.forward(450)
    turtle.right(90)
    turtle.forward(500)
    turtle.right(90)
    turtle.forward(450)
    turtle.right(90)
    turtle.forward(50)
    turtle.back(50)
    turtle.right(180)
    turtle.penup()
    turtle.forward(50)
    turtle.speed(5)
    for i in range(done_spins):
        turtle.left(360)
    
def loop():
    for i in range(loops):
        building()
        word = random.choice(colors)
        turtle.goto(0, 0)
        turtle.clearscreen()
        turtle.bgcolor("black")
        turtle.color(word)
        turtle.pensize(5)
        turtle.speed(10)
    
    turtle.write("Done!")

turtle.speed(speed)
turtle.pensize(5)

turtle.color(line_color)
if hide_tutle == 0:
    turtle.hideturtle()
elif hide_tutle == 1:
    pass
else:
    print("you dumb ass fuck go get a life you loser how can you not enter 1 or 0")
    screen.title("FUCK YOU")
    turtle.speed(100)
    turtle.hideturtle()
    turtle.color("red")
    turtle.penup()
    turtle.back(200)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(75)
    turtle.back(75)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(40)
    turtle.back(40)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.penup()
    turtle.forward(100)
    turtle.pendown()
    turtle.forward(1)
    turtle.penup()
    turtle.forward(75)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(100)
    turtle.back(100)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(100)
    time.sleep(1.25)
    os._exit()
#turtle.goto(-400, 400)
brige()
turtle.left(180)
brige()
turtle.done()